//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> PizzaID { get; set; }
        public Nullable<int> PizzaOrderID { get; set; }
    
        public virtual Pizza Pizza { get; set; }
        public virtual PizzaOrder PizzaOrder { get; set; }
    }
}
