//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStore.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pizza()
        {
            this.Orders = new HashSet<Order>();
            this.PizzaCheeses = new HashSet<PizzaChees>();
            this.PizzaToppings = new HashSet<PizzaTopping>();
        }
    
        public int PizzaID { get; set; }
        public Nullable<int> CrustID { get; set; }
        public Nullable<int> SauceID { get; set; }
        public Nullable<int> SizeID { get; set; }
    
        public virtual Crust Crust { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PizzaChees> PizzaCheeses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PizzaTopping> PizzaToppings { get; set; }
        public virtual Sauce Sauce { get; set; }
        public virtual Size Size { get; set; }
    }
}
