//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.Client.Models")]
    [System.SerializableAttribute()]
    public partial class CustomerDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.CustomerAddress addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Email emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Name nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.PhoneNumber numberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.CustomerAddress address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Email email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Name name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.PhoneNumber number {
            get {
                return this.numberField;
            }
            set {
                if ((object.ReferenceEquals(this.numberField, value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerAddress", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class CustomerAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Customer[] CustomersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((this.AddressIDField.Equals(value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddress1 {
            get {
                return this.CustomerAddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddress1Field, value) != true)) {
                    this.CustomerAddress1Field = value;
                    this.RaisePropertyChanged("CustomerAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Customer[] Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Email", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Email : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Customer[] CustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmailIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Customer[] Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email1 {
            get {
                return this.Email1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Email1Field, value) != true)) {
                    this.Email1Field = value;
                    this.RaisePropertyChanged("Email1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmailID {
            get {
                return this.EmailIDField;
            }
            set {
                if ((this.EmailIDField.Equals(value) != true)) {
                    this.EmailIDField = value;
                    this.RaisePropertyChanged("EmailID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Name", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Name : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Customer[] CustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NameIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Customer[] Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NameID {
            get {
                return this.NameIDField;
            }
            set {
                if ((this.NameIDField.Equals(value) != true)) {
                    this.NameIDField = value;
                    this.RaisePropertyChanged("NameID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneNumber", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class PhoneNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Customer[] CustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumber1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneNumberIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Customer[] Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber1 {
            get {
                return this.PhoneNumber1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumber1Field, value) != true)) {
                    this.PhoneNumber1Field = value;
                    this.RaisePropertyChanged("PhoneNumber1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhoneNumberID {
            get {
                return this.PhoneNumberIDField;
            }
            set {
                if ((this.PhoneNumberIDField.Equals(value) != true)) {
                    this.PhoneNumberIDField = value;
                    this.RaisePropertyChanged("PhoneNumberID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.CustomerAddress CustomerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Email EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EmailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Name NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.PhoneNumber PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PhoneNumberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.PizzaOrder[] PizzaOrdersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((this.AddressIDField.Equals(value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.CustomerAddress CustomerAddress {
            get {
                return this.CustomerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressField, value) != true)) {
                    this.CustomerAddressField = value;
                    this.RaisePropertyChanged("CustomerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Email Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EmailID {
            get {
                return this.EmailIDField;
            }
            set {
                if ((this.EmailIDField.Equals(value) != true)) {
                    this.EmailIDField = value;
                    this.RaisePropertyChanged("EmailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Name Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NameId {
            get {
                return this.NameIdField;
            }
            set {
                if ((this.NameIdField.Equals(value) != true)) {
                    this.NameIdField = value;
                    this.RaisePropertyChanged("NameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.PhoneNumber PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PhoneNumberID {
            get {
                return this.PhoneNumberIDField;
            }
            set {
                if ((this.PhoneNumberIDField.Equals(value) != true)) {
                    this.PhoneNumberIDField = value;
                    this.RaisePropertyChanged("PhoneNumberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.PizzaOrder[] PizzaOrders {
            get {
                return this.PizzaOrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzaOrdersField, value) != true)) {
                    this.PizzaOrdersField = value;
                    this.RaisePropertyChanged("PizzaOrders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PizzaOrder", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class PizzaOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PizzaOrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PizzaOrderID {
            get {
                return this.PizzaOrderIDField;
            }
            set {
                if ((this.PizzaOrderIDField.Equals(value) != true)) {
                    this.PizzaOrderIDField = value;
                    this.RaisePropertyChanged("PizzaOrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Pizza PizzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PizzaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.PizzaOrder PizzaOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PizzaOrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Pizza Pizza {
            get {
                return this.PizzaField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzaField, value) != true)) {
                    this.PizzaField = value;
                    this.RaisePropertyChanged("Pizza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PizzaID {
            get {
                return this.PizzaIDField;
            }
            set {
                if ((this.PizzaIDField.Equals(value) != true)) {
                    this.PizzaIDField = value;
                    this.RaisePropertyChanged("PizzaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.PizzaOrder PizzaOrder {
            get {
                return this.PizzaOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzaOrderField, value) != true)) {
                    this.PizzaOrderField = value;
                    this.RaisePropertyChanged("PizzaOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PizzaOrderID {
            get {
                return this.PizzaOrderIDField;
            }
            set {
                if ((this.PizzaOrderIDField.Equals(value) != true)) {
                    this.PizzaOrderIDField = value;
                    this.RaisePropertyChanged("PizzaOrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pizza", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Pizza : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Crust CrustField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CrustIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.PizzaChees[] PizzaCheesesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PizzaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.PizzaTopping[] PizzaToppingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Sauce SauceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SauceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Size SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SizeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Crust Crust {
            get {
                return this.CrustField;
            }
            set {
                if ((object.ReferenceEquals(this.CrustField, value) != true)) {
                    this.CrustField = value;
                    this.RaisePropertyChanged("Crust");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CrustID {
            get {
                return this.CrustIDField;
            }
            set {
                if ((this.CrustIDField.Equals(value) != true)) {
                    this.CrustIDField = value;
                    this.RaisePropertyChanged("CrustID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.PizzaChees[] PizzaCheeses {
            get {
                return this.PizzaCheesesField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzaCheesesField, value) != true)) {
                    this.PizzaCheesesField = value;
                    this.RaisePropertyChanged("PizzaCheeses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PizzaID {
            get {
                return this.PizzaIDField;
            }
            set {
                if ((this.PizzaIDField.Equals(value) != true)) {
                    this.PizzaIDField = value;
                    this.RaisePropertyChanged("PizzaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.PizzaTopping[] PizzaToppings {
            get {
                return this.PizzaToppingsField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzaToppingsField, value) != true)) {
                    this.PizzaToppingsField = value;
                    this.RaisePropertyChanged("PizzaToppings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Sauce Sauce {
            get {
                return this.SauceField;
            }
            set {
                if ((object.ReferenceEquals(this.SauceField, value) != true)) {
                    this.SauceField = value;
                    this.RaisePropertyChanged("Sauce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SauceID {
            get {
                return this.SauceIDField;
            }
            set {
                if ((this.SauceIDField.Equals(value) != true)) {
                    this.SauceIDField = value;
                    this.RaisePropertyChanged("SauceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Size Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SizeID {
            get {
                return this.SizeIDField;
            }
            set {
                if ((this.SizeIDField.Equals(value) != true)) {
                    this.SizeIDField = value;
                    this.RaisePropertyChanged("SizeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Crust", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Crust : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrustIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Pizza[] PizzasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrustID {
            get {
                return this.CrustIDField;
            }
            set {
                if ((this.CrustIDField.Equals(value) != true)) {
                    this.CrustIDField = value;
                    this.RaisePropertyChanged("CrustID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Pizza[] Pizzas {
            get {
                return this.PizzasField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzasField, value) != true)) {
                    this.PizzasField = value;
                    this.RaisePropertyChanged("Pizzas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sauce", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Sauce : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Pizza[] PizzasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SauceIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Pizza[] Pizzas {
            get {
                return this.PizzasField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzasField, value) != true)) {
                    this.PizzasField = value;
                    this.RaisePropertyChanged("Pizzas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SauceID {
            get {
                return this.SauceIDField;
            }
            set {
                if ((this.SauceIDField.Equals(value) != true)) {
                    this.SauceIDField = value;
                    this.RaisePropertyChanged("SauceID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Size", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Size : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Pizza[] PizzasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Pizza[] Pizzas {
            get {
                return this.PizzasField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzasField, value) != true)) {
                    this.PizzasField = value;
                    this.RaisePropertyChanged("Pizzas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SizeID {
            get {
                return this.SizeIDField;
            }
            set {
                if ((this.SizeIDField.Equals(value) != true)) {
                    this.SizeIDField = value;
                    this.RaisePropertyChanged("SizeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PizzaChees", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class PizzaChees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Cheese CheeseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CheeseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Pizza PizzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PizzaCheesesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PizzaIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Cheese Cheese {
            get {
                return this.CheeseField;
            }
            set {
                if ((object.ReferenceEquals(this.CheeseField, value) != true)) {
                    this.CheeseField = value;
                    this.RaisePropertyChanged("Cheese");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CheeseID {
            get {
                return this.CheeseIDField;
            }
            set {
                if ((this.CheeseIDField.Equals(value) != true)) {
                    this.CheeseIDField = value;
                    this.RaisePropertyChanged("CheeseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Pizza Pizza {
            get {
                return this.PizzaField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzaField, value) != true)) {
                    this.PizzaField = value;
                    this.RaisePropertyChanged("Pizza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PizzaCheeses {
            get {
                return this.PizzaCheesesField;
            }
            set {
                if ((this.PizzaCheesesField.Equals(value) != true)) {
                    this.PizzaCheesesField = value;
                    this.RaisePropertyChanged("PizzaCheeses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PizzaID {
            get {
                return this.PizzaIDField;
            }
            set {
                if ((this.PizzaIDField.Equals(value) != true)) {
                    this.PizzaIDField = value;
                    this.RaisePropertyChanged("PizzaID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PizzaTopping", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class PizzaTopping : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Pizza PizzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PizzaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PizzatoppingsIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Topping ToppingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ToppingIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Pizza Pizza {
            get {
                return this.PizzaField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzaField, value) != true)) {
                    this.PizzaField = value;
                    this.RaisePropertyChanged("Pizza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PizzaID {
            get {
                return this.PizzaIDField;
            }
            set {
                if ((this.PizzaIDField.Equals(value) != true)) {
                    this.PizzaIDField = value;
                    this.RaisePropertyChanged("PizzaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PizzatoppingsID {
            get {
                return this.PizzatoppingsIDField;
            }
            set {
                if ((this.PizzatoppingsIDField.Equals(value) != true)) {
                    this.PizzatoppingsIDField = value;
                    this.RaisePropertyChanged("PizzatoppingsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Topping Topping {
            get {
                return this.ToppingField;
            }
            set {
                if ((object.ReferenceEquals(this.ToppingField, value) != true)) {
                    this.ToppingField = value;
                    this.RaisePropertyChanged("Topping");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ToppingID {
            get {
                return this.ToppingIDField;
            }
            set {
                if ((this.ToppingIDField.Equals(value) != true)) {
                    this.ToppingIDField = value;
                    this.RaisePropertyChanged("ToppingID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cheese", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Cheese : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CheeseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.PizzaChees[] PizzaCheesesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CheeseID {
            get {
                return this.CheeseIDField;
            }
            set {
                if ((this.CheeseIDField.Equals(value) != true)) {
                    this.CheeseIDField = value;
                    this.RaisePropertyChanged("CheeseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.PizzaChees[] PizzaCheeses {
            get {
                return this.PizzaCheesesField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzaCheesesField, value) != true)) {
                    this.PizzaCheesesField = value;
                    this.RaisePropertyChanged("PizzaCheeses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Topping", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.DataAccess")]
    [System.SerializableAttribute()]
    public partial class Topping : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.PizzaTopping[] PizzaToppingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToppingIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.PizzaTopping[] PizzaToppings {
            get {
                return this.PizzaToppingsField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzaToppingsField, value) != true)) {
                    this.PizzaToppingsField = value;
                    this.RaisePropertyChanged("PizzaToppings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToppingID {
            get {
                return this.ToppingIDField;
            }
            set {
                if ((this.ToppingIDField.Equals(value) != true)) {
                    this.ToppingIDField = value;
                    this.RaisePropertyChanged("ToppingID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PizzaOrderDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.Client.Models")]
    [System.SerializableAttribute()]
    public partial class PizzaOrderDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PizzaOrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.CustomerDAO customerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.OrderDAO orderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PizzaOrderID {
            get {
                return this.PizzaOrderIDField;
            }
            set {
                if ((this.PizzaOrderIDField.Equals(value) != true)) {
                    this.PizzaOrderIDField = value;
                    this.RaisePropertyChanged("PizzaOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.CustomerDAO customer {
            get {
                return this.customerField;
            }
            set {
                if ((object.ReferenceEquals(this.customerField, value) != true)) {
                    this.customerField = value;
                    this.RaisePropertyChanged("customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.OrderDAO order {
            get {
                return this.orderField;
            }
            set {
                if ((object.ReferenceEquals(this.orderField, value) != true)) {
                    this.orderField = value;
                    this.RaisePropertyChanged("order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.Client.Models")]
    [System.SerializableAttribute()]
    public partial class OrderDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.PizzaDAO[] pizzasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.PizzaDAO[] pizzas {
            get {
                return this.pizzasField;
            }
            set {
                if ((object.ReferenceEquals(this.pizzasField, value) != true)) {
                    this.pizzasField = value;
                    this.RaisePropertyChanged("pizzas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PizzaDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.Client.Models")]
    [System.SerializableAttribute()]
    public partial class PizzaDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PizzaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Cheese[] cheesesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Crust crustField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Sauce sauceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Size sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Business.ServiceReference2.Topping[] toppingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PizzaID {
            get {
                return this.PizzaIDField;
            }
            set {
                if ((this.PizzaIDField.Equals(value) != true)) {
                    this.PizzaIDField = value;
                    this.RaisePropertyChanged("PizzaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Cheese[] cheeses {
            get {
                return this.cheesesField;
            }
            set {
                if ((object.ReferenceEquals(this.cheesesField, value) != true)) {
                    this.cheesesField = value;
                    this.RaisePropertyChanged("cheeses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Crust crust {
            get {
                return this.crustField;
            }
            set {
                if ((object.ReferenceEquals(this.crustField, value) != true)) {
                    this.crustField = value;
                    this.RaisePropertyChanged("crust");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Sauce sauce {
            get {
                return this.sauceField;
            }
            set {
                if ((object.ReferenceEquals(this.sauceField, value) != true)) {
                    this.sauceField = value;
                    this.RaisePropertyChanged("sauce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Size size {
            get {
                return this.sizeField;
            }
            set {
                if ((object.ReferenceEquals(this.sizeField, value) != true)) {
                    this.sizeField = value;
                    this.RaisePropertyChanged("size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Business.ServiceReference2.Topping[] toppings {
            get {
                return this.toppingsField;
            }
            set {
                if ((object.ReferenceEquals(this.toppingsField, value) != true)) {
                    this.toppingsField = value;
                    this.RaisePropertyChanged("toppings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToppingDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.Client.Models")]
    [System.SerializableAttribute()]
    public partial class ToppingDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheeseDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.Client.Models")]
    [System.SerializableAttribute()]
    public partial class CheeseDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrustDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.Client.Models")]
    [System.SerializableAttribute()]
    public partial class CrustDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SauceDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.Client.Models")]
    [System.SerializableAttribute()]
    public partial class SauceDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SizesDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStore.Client.Models")]
    [System.SerializableAttribute()]
    public partial class SizesDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomer", ReplyAction="http://tempuri.org/IService1/InsertCustomerResponse")]
        void InsertCustomer(Business.ServiceReference2.CustomerDAO c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCustomer", ReplyAction="http://tempuri.org/IService1/InsertCustomerResponse")]
        System.Threading.Tasks.Task InsertCustomerAsync(Business.ServiceReference2.CustomerDAO c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPizzaOrder", ReplyAction="http://tempuri.org/IService1/InsertPizzaOrderResponse")]
        void InsertPizzaOrder(Business.ServiceReference2.PizzaOrderDAO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPizzaOrder", ReplyAction="http://tempuri.org/IService1/InsertPizzaOrderResponse")]
        System.Threading.Tasks.Task InsertPizzaOrderAsync(Business.ServiceReference2.PizzaOrderDAO o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetToppings", ReplyAction="http://tempuri.org/IService1/GetToppingsResponse")]
        Business.ServiceReference2.ToppingDAO[] GetToppings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetToppings", ReplyAction="http://tempuri.org/IService1/GetToppingsResponse")]
        System.Threading.Tasks.Task<Business.ServiceReference2.ToppingDAO[]> GetToppingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCheeses", ReplyAction="http://tempuri.org/IService1/GetCheesesResponse")]
        Business.ServiceReference2.CheeseDAO[] GetCheeses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCheeses", ReplyAction="http://tempuri.org/IService1/GetCheesesResponse")]
        System.Threading.Tasks.Task<Business.ServiceReference2.CheeseDAO[]> GetCheesesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCrusts", ReplyAction="http://tempuri.org/IService1/GetCrustsResponse")]
        Business.ServiceReference2.CrustDAO[] GetCrusts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCrusts", ReplyAction="http://tempuri.org/IService1/GetCrustsResponse")]
        System.Threading.Tasks.Task<Business.ServiceReference2.CrustDAO[]> GetCrustsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSauces", ReplyAction="http://tempuri.org/IService1/GetSaucesResponse")]
        Business.ServiceReference2.SauceDAO[] GetSauces();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSauces", ReplyAction="http://tempuri.org/IService1/GetSaucesResponse")]
        System.Threading.Tasks.Task<Business.ServiceReference2.SauceDAO[]> GetSaucesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSizes", ReplyAction="http://tempuri.org/IService1/GetSizesResponse")]
        Business.ServiceReference2.SizesDAO[] GetSizes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSizes", ReplyAction="http://tempuri.org/IService1/GetSizesResponse")]
        System.Threading.Tasks.Task<Business.ServiceReference2.SizesDAO[]> GetSizesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Business.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Business.ServiceReference2.IService1>, Business.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertCustomer(Business.ServiceReference2.CustomerDAO c) {
            base.Channel.InsertCustomer(c);
        }
        
        public System.Threading.Tasks.Task InsertCustomerAsync(Business.ServiceReference2.CustomerDAO c) {
            return base.Channel.InsertCustomerAsync(c);
        }
        
        public void InsertPizzaOrder(Business.ServiceReference2.PizzaOrderDAO o) {
            base.Channel.InsertPizzaOrder(o);
        }
        
        public System.Threading.Tasks.Task InsertPizzaOrderAsync(Business.ServiceReference2.PizzaOrderDAO o) {
            return base.Channel.InsertPizzaOrderAsync(o);
        }
        
        public Business.ServiceReference2.ToppingDAO[] GetToppings() {
            return base.Channel.GetToppings();
        }
        
        public System.Threading.Tasks.Task<Business.ServiceReference2.ToppingDAO[]> GetToppingsAsync() {
            return base.Channel.GetToppingsAsync();
        }
        
        public Business.ServiceReference2.CheeseDAO[] GetCheeses() {
            return base.Channel.GetCheeses();
        }
        
        public System.Threading.Tasks.Task<Business.ServiceReference2.CheeseDAO[]> GetCheesesAsync() {
            return base.Channel.GetCheesesAsync();
        }
        
        public Business.ServiceReference2.CrustDAO[] GetCrusts() {
            return base.Channel.GetCrusts();
        }
        
        public System.Threading.Tasks.Task<Business.ServiceReference2.CrustDAO[]> GetCrustsAsync() {
            return base.Channel.GetCrustsAsync();
        }
        
        public Business.ServiceReference2.SauceDAO[] GetSauces() {
            return base.Channel.GetSauces();
        }
        
        public System.Threading.Tasks.Task<Business.ServiceReference2.SauceDAO[]> GetSaucesAsync() {
            return base.Channel.GetSaucesAsync();
        }
        
        public Business.ServiceReference2.SizesDAO[] GetSizes() {
            return base.Channel.GetSizes();
        }
        
        public System.Threading.Tasks.Task<Business.ServiceReference2.SizesDAO[]> GetSizesAsync() {
            return base.Channel.GetSizesAsync();
        }
    }
}
